# basic options
title: 양정고 59회 동기회
author: 양정고 59회 동기회
email: kdoh@me.com
description: 양정고등학교 59회 동기회 홈페이지
twitter_username:
github_username: Yc59home

# Build settings
markdown: kramdown
theme: minima
